import assert from 'node:assert/strict';
import { closeSync, mkdtempSync, openSync, readFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { DatabaseSync } from 'node:sqlite';
import test from 'node:test';
import { openMemoryCore } from '../contract.mjs';

// Frozen fresh synthetic v9 database generated by the checked-in stdout recipe
// against unmodified base 3512719a3c43c14354f76c31064d8d62666e97bf, Node22.16.0.
// Scripted capture supplies ordered receipts only; it proves no model semantics.
const saved = JSON.parse(readFileSync(new URL('./claim-qualification-v9-fixture.json', import.meta.url), 'utf8'));
const ok = (r) => { assert.equal(r.ok, true, JSON.stringify(r)); return r.value; };
function fixture(t) {
  const path = join(mkdtempSync(join(tmpdir(), 'cairn-qualification-v9-')), 'memory.sqlite');
  closeSync(openSync(path, 'ax', 0o600)); const db = new DatabaseSync(path); t.after(() => db.close());
  for (const type of ['table', 'index', 'view']) for (const row of saved.schema.filter((r) => r.type === type)) db.exec(row.sql);
  db.exec('BEGIN; PRAGMA defer_foreign_keys=ON');
  for (const { name, rows } of saved.tables) for (const row of rows) {
    const columns = Object.keys(row);
    db.prepare(`INSERT INTO "${name}" (${columns.map((c) => `"${c}"`).join(',')}) VALUES (${columns.map(() => '?').join(',')})`).run(...Object.values(row));
  }
  db.exec('COMMIT'); assert.deepEqual(db.prepare('PRAGMA foreign_key_check').all(), []);
  for (const row of saved.schema.filter((r) => r.type === 'trigger')) db.exec(row.sql);
  db.exec('PRAGMA application_id=1128352082; PRAGMA user_version=9');
  return { path, db };
}
function preserved(db) {
  for (const { name, rows } of saved.tables)
    assert.deepEqual(db.prepare(`SELECT * FROM "${name}" ORDER BY rowid`).all().map((row) => ({ ...row })), rows, name);
}

test('S7 frozen v9 migration preserves all old identities, records, ordered sources, replay, cursors and index state without backfill', async (t) => {
  const { path, db } = fixture(t); const core = openMemoryCore({ path }); t.after(() => core.close());
  assert.equal(db.prepare('PRAGMA user_version').get().user_version, 11); preserved(db);
  for (const name of ['memory_qualifications', 'qualification_anchors']) {
    assert.equal(db.prepare(`SELECT count(*) n FROM ${name}`).get().n, 0);
    assert.equal(db.prepare('PRAGMA table_list').all().find((r) => r.name === name).strict, 1);
  }
  assert.deepEqual(ok(core.get({ namespace: saved.namespace, memoryId: saved.history.memory.id })), saved.history);
  assert.deepEqual(ok(core.get({ namespace: saved.namespace, memoryId: saved.history.memory.id, includeQualification: true })),
    { ...saved.history, qualification: null });
  assert.deepEqual(ok(core.list({ namespace: saved.namespace, limit: 1, cursor: saved.cursor })), saved.next);
  assert.deepEqual(ok(core.claimAdmission({ ...saved.key, leaseMs: 1000 })), { duplicate: true, memoryIds: [], suppressedCount: 0 });
  const replay = ok(await core.capture(saved.captureInput));
  assert.equal(replay.duplicate, true);
  assert.deepEqual(replay.memoryIds, saved.captureResult.admission.memories.map((m) => m.id));
  preserved(db);
  core.close(); const reopened = openMemoryCore({ path }); t.after(() => reopened.close());
  assert.equal(db.prepare('PRAGMA user_version').get().user_version, 11); preserved(db);
  let cursor = saved.rebuild.cursor;
  do { cursor = ok(reopened.rebuildIndex({ ...saved.rebuild, cursor })).nextCursor; } while (cursor);
  assert.deepEqual(db.prepare('PRAGMA foreign_key_check').all(), []);
});

for (const table of ['memory_qualifications', 'qualification_anchors']) test(`S7 collision at ${table} rolls back all DDL and preserves v9 data`, (t) => {
  const { path, db } = fixture(t);
  db.exec(`CREATE TABLE ${table}(preserve_me TEXT); INSERT INTO ${table} VALUES ('synthetic survivor')`);
  const schema = db.prepare('SELECT * FROM sqlite_master ORDER BY name').all();
  assert.throws(() => openMemoryCore({ path }));
  assert.equal(db.prepare('PRAGMA user_version').get().user_version, 9);
  assert.deepEqual(db.prepare('SELECT * FROM sqlite_master ORDER BY name').all(), schema); preserved(db);
  assert.equal(db.prepare(`SELECT preserve_me FROM ${table}`).get().preserve_me, 'synthetic survivor');
  db.exec(`DROP TABLE ${table}`); const core = openMemoryCore({ path }); t.after(() => core.close());
  assert.equal(db.prepare('PRAGMA user_version').get().user_version, 11); preserved(db);
});

test('S7 writer lock blocks migration with no partial v10 state, then clean retry succeeds', (t) => {
  const { path, db } = fixture(t); const schema = db.prepare('SELECT * FROM sqlite_master ORDER BY name').all();
  db.exec('BEGIN IMMEDIATE');
  try {
    assert.throws(() => openMemoryCore({ path }));
    assert.equal(db.prepare('PRAGMA user_version').get().user_version, 9);
    assert.deepEqual(db.prepare('SELECT * FROM sqlite_master ORDER BY name').all(), schema); preserved(db);
  } finally { db.exec('ROLLBACK'); }
  const core = openMemoryCore({ path }); t.after(() => core.close());
  assert.equal(db.prepare('PRAGMA user_version').get().user_version, 11); preserved(db);
});
