// Generated by integrations/client/bundle.mjs. Do not edit.
import { homedir, tmpdir } from 'node:os';
import { isAbsolute, join, resolve, relative } from 'node:path';
import { opendir, readFile, readlink, unlink } from 'node:fs/promises';
import { randomUUID } from 'node:crypto';
import { privateDirectory, privateRead, privateWrite, checkedPath } from './private-state.mjs';
import { withFileLock } from './file-lock.mjs';
import { opaqueProjectId, projectKey } from './identity.mjs';
import { setPaused, readControlState } from './control-state.mjs';

const CLIENTS = ['claude', 'codex'];
const fail = message => { throw new Error(message); };
const absolute = value => typeof value === 'string' && isAbsolute(value) && resolve(value) === value;

export function stateLocations({ home = homedir(), temporary = tmpdir(), env = process.env, setup = false } = {}) {
  if (setup && !absolute(home)) fail('Cannot determine an absolute home directory; setup made no changes.');
  const base = home || temporary;
  if (!absolute(base)) fail('invalid_home');
  const coordination = join(base, '.cairn-memory-clients');
  return { home, temporary, coordination, install: join(coordination, 'install.json'),
    pairing: join(coordination, 'pairing.json'), lock: join(coordination, 'setup.lock'),
    defaultRoot: join(base, '.cairn-memory'),
    claudeRoot: env.CLAUDE_PLUGIN_DATA ?? join(base, '.cairn-memory'),
    knownClaudeRoot: env.CLAUDE_PLUGIN_DATA ?? join(base, '.claude/plugins/data/cairn-memory-cairn-memory') };
}

async function jsonFile(path) {
  const text = await privateRead(path, { missing: true });
  if (text === undefined) return undefined;
  try { return JSON.parse(text); } catch { fail('invalid_pairing_metadata'); }
}
function validateInstall(value) {
  if (!value) return { version: 1, clients: {} };
  if (value.version !== 1 || !value.clients || typeof value.clients !== 'object' || Array.isArray(value.clients)) fail('invalid_install');
  for (const [client, binding] of Object.entries(value.clients)) {
    if (!CLIENTS.includes(client) || !absolute(binding?.root) || !['established', 'pending'].includes(binding?.state)) fail('invalid_install');
  }
  if (value.shared && (!absolute(value.shared.root) || typeof value.shared.id !== 'string' ||
    !['initialize-shared', 'adopt-existing'].includes(value.shared.policy) ||
    typeof value.shared.initialized !== 'boolean' || typeof value.shared.ready !== 'boolean')) fail('invalid_install');
  return value;
}
function validateRecord(record, locations) {
  if (!record || record.version !== 1 || !absolute(record.root) ||
      !Array.isArray(record.participants) || record.participants.length !== 2 ||
      !CLIENTS.every(client => record.participants.includes(client)) ||
      !['initialize-shared', 'adopt-existing'].includes(record.policy) ||
      typeof record.id !== 'string' || typeof record.namespace !== 'string') fail('invalid_pairing_record');
  durable(record.root, locations);
  return record;
}
function durable(root, locations) {
  if (!absolute(locations.home) || !absolute(root)) fail('pairing_requires_durable_home');
  // Test homes may be under TMPDIR; the durable logical boundary is the explicit home.
  // Outside it, reject the known temporary-storage trees.
  const beneath = (parent, child) => child === parent || (!relative(parent, child).startsWith('..') && !isAbsolute(relative(parent, child)));
  if (!beneath(locations.home, root) && [locations.temporary, '/tmp', '/var/tmp'].some(path => beneath(path, root))) fail('temporary_pairing_root');
}
async function keyPresent(root) {
  if (!absolute(root)) fail('invalid_state_path');
  const bytes = await privateRead(join(root, 'project-key'), { missing: true });
  if (bytes === undefined) return false;
  await checkedPath(root, { directory: true });
  // Validate without creating anything during detection.
  if (!/^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(bytes.trim())) fail('invalid_identity: project-key');
  return true;
}

/** Bounded metadata-only evidence in Cairn's root; never read a host transcript. */
export async function hasClaudeEvidence(root) {
  const directory = join(root, 'sessions');
  if (!await checkedPath(directory, { directory: true, missing: true })) return false;
  const entries = await opendir(directory);
  let count = 0;
  for await (const entry of entries) {
    if (++count > 256) return false; // Absence/uncertainty requires confirmation.
    if (!/^[a-f0-9]{64}\.json$/.test(entry.name)) continue;
    const value = await jsonFile(join(directory, entry.name));
    if (Number.isSafeInteger(value?.offset) && value.offset >= 0) return true;
  }
  return false;
}

/** Read-only, exact known-file checks. Unknown Claude origins need a setup answer. */
export async function detectClients(options = {}) {
  const locations = stateLocations(options);
  if (await checkedPath(locations.coordination, { directory: true, missing: true })) { /* validated */ }
  const install = validateInstall(await jsonFile(locations.install));
  const record = await jsonFile(locations.pairing);
  if (record) validateRecord(record, locations);
  const roots = [...new Set([locations.defaultRoot, locations.knownClaudeRoot, locations.claudeRoot,
    ...Object.values(install.clients).map(binding => binding.root), ...(record ? [record.root] : []), ...(install.resetPending ? [install.resetPending.root] : [])])];
  const keys = [];
  for (const root of roots) if (await keyPresent(root)) keys.push(root);
  return { locations, install, record, keys };
}

/** Namespace identity is a lock-liveness seam, not a caller assertion of consent. */
export async function localLiveness() {
  if (process.platform !== 'linux') return { namespace: undefined, isAlive: () => true };
  const namespace = `${(await readFile('/proc/sys/kernel/random/boot_id', 'utf8')).trim()}:${await readlink('/proc/self/ns/pid')}`;
  return { namespace, isAlive(pid) {
    try { process.kill(pid, 0); return true; } catch (error) { return error.code !== 'ESRCH'; }
  } };
}
async function locked(options, work) {
  // Detection is deliberately before even creating the coordination directory.
  await detectClients(options);
  const locations = stateLocations(options);
  const liveness = options.liveness ?? await localLiveness();
  if (options.setup && !liveness.namespace) fail('pid_namespace_unverified');
  await privateDirectory(locations.coordination);
  await checkedPath(locations.lock, { missing: true });
  let result;
  const acquired = await withFileLock(locations.lock, async () => {
    result = await work(await detectClients(options), liveness);
  }, { timeoutMs: options.timeoutMs ?? 2000, pollMs: 10,
    context: { namespace: liveness.namespace ?? 'unverified' }, isAlive: liveness.isAlive,
    validatePath: path => checkedPath(path, { missing: true }),
    validateOwner: async owner => {
      if (!owner || !liveness.namespace || owner.namespace !== liveness.namespace) fail('pid_namespace_unverified');
    } });
  if (!acquired) fail('setup_busy');
  return result;
}
const saveInstall = (locations, install) => privateWrite(locations.install, JSON.stringify(install));
const disabled = (status = 'pairing_needed') => ({ status, enabled: false });

export function parsePairingRecord(argv = []) {
  let pairingRecord;
  const rest = [];
  for (let i = 0; i < argv.length; i++) {
    if (argv[i] !== '--pairing-record') { rest.push(argv[i]); continue; }
    if (pairingRecord !== undefined || !absolute(argv[i + 1])) fail('invalid_pairing_argument');
    pairingRecord = argv[++i];
  }
  return { pairingRecord, rest };
}

/** Resolve root eligibility; CAIRN_MEMORY_STATE_DIR is only a checked handoff. */
export async function resolveClient(options = {}) {
  const { client = 'claude', env = process.env, initialize = false } = options;
  if (!CLIENTS.includes(client)) fail('invalid_client');
  if (options.pairingRecord !== undefined && client === 'claude' && env.CLAUDE_PLUGIN_OPTION_PAIRING_RECORD !== undefined && options.pairingRecord !== env.CLAUDE_PLUGIN_OPTION_PAIRING_RECORD) fail('pairing_record_mismatch');
  const delivered = options.pairingRecord ?? (client === 'claude' ? env.CLAUDE_PLUGIN_OPTION_PAIRING_RECORD : undefined);
  return locked(options, async ({ locations, install, record, keys }, liveness) => {
    if (install.resetPending) return disabled();
    const binding = install.clients[client];
    if (delivered !== undefined) {
      if (!absolute(delivered) || delivered !== locations.pairing) fail('pairing_record_mismatch');
      if (!record) fail('pairing_record_missing');
    }
    if (record || install.shared || binding?.state === 'pending') {
      if (!record || !delivered || !install.shared?.ready) return disabled();
      if (record.namespace !== liveness.namespace || !liveness.namespace) fail('pid_namespace_unverified');
      if (!binding || binding.state !== 'established' || binding.root !== record.root ||
          !install.shared.initialized || install.shared.id !== record.id || install.shared.root !== record.root ||
          install.shared.policy !== record.policy) fail('pairing_record_mismatch');
      if (env.CAIRN_MEMORY_STATE_DIR !== undefined && env.CAIRN_MEMORY_STATE_DIR !== record.root) fail('state_dir_mismatch');
      if (!keys.includes(record.root)) return disabled('paired_key_missing');
      return { enabled: true, status: 'paired', root: record.root, paired: true,
        workerEnv: { ...env, CAIRN_MEMORY_STATE_DIR: record.root } };
    }
    let root = binding?.root ?? (client === 'claude' ? locations.claudeRoot : (options.root ?? locations.defaultRoot));
    if (!absolute(root)) fail('invalid_state_path');
    const other = install.clients[CLIENTS.find(name => name !== client)];
    // A default-root cursor predates newly exported CLAUDE_PLUGIN_DATA.
    const legacyClaude = client === 'claude' && keys.includes(locations.defaultRoot) && await hasClaudeEvidence(locations.defaultRoot);
    if (!binding && legacyClaude) root = locations.defaultRoot;
    let established = binding?.state === 'established';
    if (!established && client === 'claude' && keys.includes(root)) {
      established = !other || other.root !== root || legacyClaude;
    }
    const conflict = !!other || keys.some(keyRoot => keyRoot !== root) ||
      (client === 'codex' && !established && keys.length > 0);
    if (!established && conflict) return disabled();
    if (client === 'codex' && !established && !options.standardClaudeOrigin && options.usesClaude !== false) return disabled();
    if (env.CAIRN_MEMORY_STATE_DIR !== undefined && env.CAIRN_MEMORY_STATE_DIR !== root) fail('state_dir_mismatch');
    if (conflict && !keys.includes(root)) return disabled();
    await privateDirectory(root);
    if (!binding) {
      install.clients[client] = { root, state: 'established' };
      await saveInstall(locations, install);
    }
    if (initialize) {
      await projectKey(root, { create: !conflict, checkpoint: options.checkpoint });
      install.clients[client].initialized = true;
      await saveInstall(locations, install);
    }
    return { enabled: true, status: conflict ? 'pairing_needed' : 'single', root, paired: false,
      workerEnv: { ...env, CAIRN_MEMORY_STATE_DIR: root } };
  });
}

export async function clientProjectId(options, cwd) {
  if (!cwd) return undefined;
  const binding = await resolveClient({ ...options, initialize: true });
  if (!binding.enabled) fail(binding.status);
  return opaqueProjectId(binding.root, cwd, { create: false });
}

/** CX-7 API: no host execution. Caller obtains consent and stops hosts/workers. */
export async function initializePairing(options = {}) {
  const setupOptions = { ...options, setup: true };
  const locations = stateLocations(setupOptions); // refuse bad home before writes
  if (options.hostsStopped !== true || !CLIENTS.every(client => options.consent?.[client] === true)) fail('pairing_consent_required');
  const root = options.root ?? locations.defaultRoot;
  durable(root, locations);
  const initial = await detectClients(setupOptions);
  if (initial.record && !initial.install.shared) fail('pairing_record_mismatch');
  if (!options.standardClaudeOrigin && options.usesClaude === undefined) return { status: 'claude_confirmation_needed', enabled: false };
  if (!initial.install.shared && (initial.keys.length || Object.keys(initial.install.clients).length || options.usesClaude === true) && options.adopt !== true) return disabled();
  return locked(setupOptions, async ({ install, keys, record: existingRecord }, liveness) => {
    if (!liveness.namespace || (existingRecord && existingRecord.namespace !== liveness.namespace)) fail('pid_namespace_unverified');
    if (existingRecord && (!install.shared || !install.shared.initialized)) fail('pairing_record_mismatch');
    if (install.resetPending) fail('identity_reset_pending');
    if (install.shared && (install.shared.root !== root || (existingRecord && existingRecord.id !== install.shared.id))) fail('pending_binding_mismatch');
    if (!install.shared) {
      if ((keys.length || Object.keys(install.clients).length || options.usesClaude === true) && options.adopt !== true) return disabled();
      if (options.adoptFrom && !options.adopt) fail('adoption_confirmation_required');
      if (options.adopt && !await keyPresent(options.adoptFrom ?? root)) fail('adopted_key_missing');
      if (options.adoptFrom && await keyPresent(root) &&
          await projectKey(root, { create: false }) !== await projectKey(options.adoptFrom, { create: false })) fail('adoption_key_conflict');
      install.shared = { id: randomUUID(), root, policy: options.adopt ? 'adopt-existing' : 'initialize-shared', initialized: false, ready: false,
        ...(options.adoptFrom ? { adoptFrom: options.adoptFrom } : {}) };
      for (const client of CLIENTS) install.clients[client] = { root, state: 'pending' };
      await saveInstall(locations, install);
      await options.checkpoint?.('binding-written');
    }
    if (options.adoptFrom && (!options.adopt || install.shared.adoptFrom !== options.adoptFrom)) fail('pending_binding_mismatch');
    if (!install.shared.initialized) {
      if (install.shared.adoptFrom && !await keyPresent(root)) {
        const source = await projectKey(install.shared.adoptFrom, { create: false });
        await privateWrite(join(root, 'project-key'), `${source}\n`, { exclusive: true, checkpoint: options.checkpoint });
        if (await projectKey(root, { create: false }) !== source) fail('adoption_key_conflict');
      }
      // Retrying after publication always reads the winner. Adoption never creates.
      await projectKey(root, { create: install.shared.policy === 'initialize-shared', checkpoint: options.checkpoint });
      install.shared.initialized = true;
      await saveInstall(locations, install);
      await options.checkpoint?.('initialized');
    } else if (!await keyPresent(root)) return disabled('paired_key_missing');
    const record = { version: 1, id: install.shared.id, root, participants: CLIENTS,
      policy: install.shared.policy, namespace: liveness.namespace };
    await privateWrite(locations.pairing, JSON.stringify(record));
    // Establish the EOF barrier before either client can become active.
    if (!install.shared.barrier) {
      const before = await readControlState(root);
      await setPaused(root, true, { rotate: true });
      if (!before.paused) await setPaused(root, false);
      install.shared.barrier = true;
      await saveInstall(locations, install);
    }
    return { status: install.shared.ready ? 'paired' : 'binding_pending', enabled: install.shared.ready,
      pairingRecord: locations.pairing, root };
  });
}

/** Call only after BOTH hook configurations have the record and workers are stopped. */
export async function completePairing(options = {}) {
  if (options.hostsStopped !== true || !CLIENTS.every(client => options.configured?.[client] === true)) fail('binding_configuration_required');
  return locked({ ...options, setup: true }, async ({ install, record, locations, keys }, liveness) => {
    if (install.resetPending) fail('identity_reset_pending');
    if (!record || !install.shared?.initialized || !install.shared.barrier ||
        install.shared.id !== record.id || install.shared.root !== record.root ||
        record.namespace !== liveness.namespace) fail('pending_binding_mismatch');
    if (!keys.includes(record.root)) return disabled('paired_key_missing');
    for (const client of CLIENTS) install.clients[client] = { root: record.root, state: 'established' };
    install.shared.ready = true;
    await saveInstall(locations, install);
    return { status: 'paired', enabled: true, pairingRecord: locations.pairing, root: record.root };
  });
}

/** Explicit stopped-worker identity reset; old roots and memories are retained. */
export async function resetIdentity(options = {}) {
  if (options.confirmIdentityReset !== true || options.hostsStopped !== true ||
      !CLIENTS.includes(options.primaryClient)) fail('identity_reset_confirmation_required');
  const locations = stateLocations({ ...options, setup: true });
  durable(options.root, locations);
  return locked({ ...options, setup: true }, async ({ install, record, keys }) => {
    if (!install.shared || (!record && !install.resetPending) || options.root === install.shared.root ||
        (keys.includes(options.root) && !install.resetPending)) fail('identity_reset_requires_new_root');
    if (install.resetPending && install.resetPending.root !== options.root) fail('pending_binding_mismatch');
    install.resetPending = { root: options.root, client: options.primaryClient };
    await saveInstall(locations, install);
    await projectKey(options.root);
    await setPaused(options.root, true, { rotate: true });
    const retired = [...(install.retired ?? []), { ...install.shared, invalidated: true }];
    await unlink(locations.pairing).catch(error => { if (error.code !== "ENOENT") throw error; });
    await saveInstall(locations, { version: 1, retired, clients: {
      [options.primaryClient]: { root: options.root, state: 'established', initialized: true }
    } });
    return { status: 'identity_reset', root: options.root,
      disclosure: 'Old project memories are no longer addressable by the new identity; the second client requires explicit adoption. Resume starts at EOF.' };
  });
}
