// Generated by integrations/client/bundle.mjs. Do not edit.
import { homedir, tmpdir, uptime } from "node:os";
import { isAbsolute, join, resolve, relative } from "node:path";
import {
  opendir,
  readFile,
  readlink,
  unlink,
  lstat,
  stat,
  access,
  realpath,
} from "node:fs/promises";
import { constants } from "node:fs";
import { createHmac, randomUUID } from "node:crypto";
import { privateDirectory, privateRead, privateWrite, checkedPath } from "./private-state.mjs";
import { withFileLock } from "./file-lock.mjs";
import { opaqueProjectId, projectKey, rootMarker, restoreProjectKey } from "./identity.mjs";
import { setPaused, readControlState } from "./control-state.mjs";

const CLIENTS = ["claude", "codex"];
const fail = (message) => {
  throw new Error(message);
};
const absolute = (value) =>
  typeof value === "string" &&
  !value.includes("\0") &&
  isAbsolute(value) &&
  resolve(value) === value;

const normalizeRoot = (root) =>
  typeof root === "string" && isAbsolute(root) ? resolve(root) : root;
const beneath = (parent, child) =>
  child === parent ||
  (!relative(parent, child).startsWith("..") && !isAbsolute(relative(parent, child)));

export function stateLocations({
  home = homedir(),
  temporary = tmpdir(),
  env = process.env,
  setup = false,
} = {}) {
  if (setup && !absolute(home))
    fail("Cannot determine an absolute home directory; setup made no changes.");
  const base = home || temporary;
  const coordination = join(base, ".cairn-memory-clients");
  return {
    home,
    temporary,
    coordination,
    install: join(coordination, "install.json"),
    pairing: join(coordination, "pairing.json"),
    lock: join(coordination, "setup.lock"),
    defaultRoot: join(base, ".cairn-memory"),
    claudeRoot: normalizeRoot(env.CLAUDE_PLUGIN_DATA ?? join(base, ".cairn-memory")),
    knownClaudeRoot:
      env.CLAUDE_PLUGIN_DATA ?? join(base, ".claude/plugins/data/cairn-memory-cairn-memory"),
  };
}

async function jsonFile(path) {
  const text = await privateRead(path, { missing: true });
  if (text === undefined) return undefined;
  try {
    return JSON.parse(text);
  } catch {
    fail("invalid_pairing_metadata");
  }
}
function validateInstall(value) {
  if (!value) return { version: 1, clients: {} };
  if (
    value.version !== 1 ||
    !value.clients ||
    typeof value.clients !== "object" ||
    Array.isArray(value.clients)
  )
    fail("invalid_install");
  for (const [client, binding] of Object.entries(value.clients)) {
    if (
      !CLIENTS.includes(client) ||
      !absolute(binding?.root) ||
      (client === "claude" && !absolute(binding.profileRoot)) ||
      !["established", "pending"].includes(binding?.state)
    )
      fail("invalid_install");
  }
  if (
    value.shared &&
    (!absolute(value.shared.root) ||
      typeof value.shared.id !== "string" ||
      !["initialize-shared", "adopt-existing"].includes(value.shared.policy) ||
      typeof value.shared.initialized !== "boolean" ||
      typeof value.shared.ready !== "boolean")
  )
    fail("invalid_install");
  if (
    value.retired !== undefined &&
    (!Array.isArray(value.retired) ||
      value.retired.some(
        (entry) => !entry || !absolute(entry.claude?.profileRoot) || !absolute(entry.claude?.root),
      ))
  )
    fail("invalid_install");
  return value;
}
// Retired ownership still identifies the profile that must explicitly re-adopt.
function claudeRegistration(install) {
  return install.clients.claude ?? install.retired?.at(-1)?.claude;
}

function validateRecord(record, locations) {
  if (
    !record ||
    record.version !== 1 ||
    !absolute(record.root) ||
    !Array.isArray(record.participants) ||
    record.participants.length !== 2 ||
    !CLIENTS.every((client) => record.participants.includes(client)) ||
    !["initialize-shared", "adopt-existing"].includes(record.policy) ||
    typeof record.id !== "string"
  )
    fail("invalid_pairing_record");
  durable(record.root, locations);
  return record;
}
function durable(root, locations) {
  if (!absolute(locations.home) || !absolute(root)) fail("pairing_requires_durable_home");
  // Test homes may be under TMPDIR; the durable logical boundary is the explicit home.
  // Outside it, reject the known temporary-storage trees.
  if (
    !beneath(locations.home, root) &&
    [locations.temporary, "/tmp", "/var/tmp"].some((path) => beneath(path, root))
  )
    fail("temporary_pairing_root");
}
async function requireTemporarySource(root, locations) {
  if (!absolute(root)) fail("adopt_from_requires_temporary_root");
  const source = await realpath(root);
  const home = await realpath(locations.home);
  const temporaryRoots = (
    await Promise.all(
      [locations.temporary, "/tmp", "/var/tmp"].map((path) =>
        probe(() => realpath(path), undefined),
      ),
    )
  ).filter(Boolean);
  if (beneath(home, source) || !temporaryRoots.some((parent) => beneath(parent, source)))
    fail("adopt_from_requires_temporary_root");
}

async function keyPresent(root, { strict = false } = {}) {
  if (strict && !absolute(root)) fail("invalid_state_path");
  let bytes;
  if (strict) {
    await checkedPath(root, { directory: true, missing: true });
    bytes = await privateRead(join(root, "project-key"), { missing: true });
  } else {
    // Read-only discovery must preserve released Claude's host-owned paths.
    try {
      bytes = await readFile(join(root, "project-key"), "utf8");
    } catch (error) {
      if (error.code !== "ENOENT") throw error;
    }
  }
  if (bytes === undefined) return false;
  if (!/^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(bytes.trim()))
    fail("invalid_identity: project-key");
  return true;
}

/** Bounded metadata-only evidence in Cairn's root; never read a host transcript. */
export async function hasClaudeEvidence(root) {
  const directory = join(root, "sessions");
  if (!(await checkedPath(directory, { directory: true, missing: true }))) return false;
  const entries = await opendir(directory);
  let count = 0;
  for await (const entry of entries) {
    if (++count > 256) return false; // Absence/uncertainty requires confirmation.
    if (!/^[a-f0-9]{64}\.json$/.test(entry.name)) continue;
    const value = await jsonFile(join(directory, entry.name));
    if (Number.isSafeInteger(value?.offset) && value.offset >= 0) return true;
  }
  return false;
}

/** Read-only, exact known-file checks. Unknown Claude origins need a setup answer. */
export async function detectClients(options = {}) {
  const locations = stateLocations(options);
  if (options.claudeProfileRoot !== undefined && !absolute(options.claudeProfileRoot))
    fail("invalid_claude_profile_root");
  if (await checkedPath(locations.coordination, { directory: true, missing: true })) {
    /* validated */
  }
  const install = validateInstall(await jsonFile(locations.install));
  const record = await jsonFile(locations.pairing);
  if (record) validateRecord(record, locations);
  const roots = [
    ...new Set([
      locations.defaultRoot,
      locations.knownClaudeRoot,
      locations.claudeRoot,
      ...(options.claudeProfileRoot === undefined ? [] : [options.claudeProfileRoot]),
      ...Object.values(install.clients).map((binding) => binding.root),
      ...(record ? [record.root] : []),
      ...(install.resetPending ? [install.resetPending.root] : []),
    ]),
  ];
  const keys = [];
  for (const root of roots) if (await keyPresent(root)) keys.push(root);
  return { locations, install, record, keys };
}

/** Boot and namespace identity belong to lock owners, not durable bindings. */
export async function localLiveness({ platform = process.platform } = {}) {
  const isAlive = (pid) => {
    try {
      process.kill(pid, 0);
      return true;
    } catch (error) {
      return error.code !== "ESRCH";
    }
  };
  if (platform === "linux") {
    return {
      boot: (await readFile("/proc/sys/kernel/random/boot_id", "utf8")).trim(),
      namespace: await readlink("/proc/self/ns/pid"),
      platform,
      isAlive,
    };
  }
  if (platform === "darwin") {
    // os.uptime is system uptime in seconds. Allow two seconds of sampling/
    // rounding drift when comparing estimates from separate processes.
    return { boot: Date.now() - uptime() * 1000, namespace: "darwin", platform, isAlive };
  }
  return { platform, namespace: undefined, boot: undefined, isAlive };
}

function ownerAlive(owner, liveness) {
  if (!owner || !liveness.namespace) fail("pid_namespace_unverified");
  const differentBoot =
    owner.boot !== undefined &&
    liveness.boot !== undefined &&
    (typeof owner.boot === "number" && typeof liveness.boot === "number"
      ? Math.abs(owner.boot - liveness.boot) > 2000
      : owner.boot !== liveness.boot);
  // After reboot even a reused PID cannot be this lock's owner. Namespace
  // comparison is meaningful only within one boot.
  if (differentBoot) return false;
  if (owner.namespace !== liveness.namespace) fail("pid_namespace_unverified");
  return liveness.isAlive(owner.pid);
}

async function locked(options, work) {
  const inspect = options.claudeFacts ? probeClaudeFacts : detectClients;
  await inspect(options);
  const locations = stateLocations(options);
  const liveness = options.liveness ?? (await localLiveness());
  // Unsupported lock ownership must not create coordination and turn an
  // otherwise fresh standalone install into degraded state (notably Windows).
  if (!liveness.namespace) fail("pairing_platform_unsupported");
  await privateDirectory(locations.coordination);
  await checkedPath(locations.lock, { missing: true });
  await options.beforeSetupLock?.();
  let result;
  const acquired = await withFileLock(
    locations.lock,
    async () => {
      result = await work(await inspect(options), liveness);
    },
    {
      timeoutMs: options.timeoutMs ?? 2000,
      pollMs: 10,
      context: { namespace: liveness.namespace, boot: liveness.boot },
      isAlive: (_pid, owner) => ownerAlive(owner, liveness),
      validatePath: (path) => checkedPath(path, { missing: true }),
      read: (path) => privateRead(path, { missing: true }),
      validateOwner: async (owner) => {
        ownerAlive(owner, liveness);
      },
    },
  );
  if (!acquired) fail("setup_busy");
  return result;
}
const saveInstall = (locations, install) =>
  privateWrite(locations.install, JSON.stringify(validateInstall(install)));
const disabled = (status = "pairing_needed", detail) => ({
  status,
  enabled: false,
  ...(detail ? { detail } : {}),
});

export function parsePairingRecord(argv = []) {
  let pairingRecord;
  const rest = [];
  for (let i = 0; i < argv.length; i++) {
    if (argv[i] !== "--pairing-record") {
      rest.push(argv[i]);
      continue;
    }
    if (pairingRecord !== undefined || !absolute(argv[i + 1])) fail("invalid_pairing_argument");
    pairingRecord = argv[++i];
  }
  return { pairingRecord, rest };
}

async function activeBinding(root, env, status = "single", paired = false) {
  if (await retiredRoot(root)) return disabled("pairing_needed", "retired root");
  if (paired && env.CAIRN_MEMORY_STATE_DIR !== undefined && env.CAIRN_MEMORY_STATE_DIR !== root) {
    fail("state_dir_mismatch");
  }
  return {
    enabled: true,
    status,
    root,
    paired,
    workerEnv: { ...env, CAIRN_MEMORY_STATE_DIR: root },
  };
}

async function selectCodexBinding(options, snapshot, delivered) {
  const { client = "claude", env = process.env } = options;
  const { locations, install, record, keys } = snapshot;
  const binding = install.clients[client];
  if (delivered !== undefined) {
    if (!absolute(delivered) || delivered !== locations.pairing) {
      fail("pairing_record_mismatch");
    }
    if (!record) fail("pairing_record_missing");
  }
  if (install.resetPending) return disabled();
  if (record || install.shared || binding?.state === "pending") {
    if (!record || !delivered || !install.shared?.ready) return disabled();
    if (process.platform === "win32") fail("pairing_platform_unsupported");
    if (
      !binding ||
      binding.state !== "established" ||
      binding.root !== record.root ||
      !install.shared.initialized ||
      install.shared.id !== record.id ||
      install.shared.root !== record.root ||
      install.shared.policy !== record.policy
    ) {
      fail("pairing_record_mismatch");
    }
    if (await retiredRoot(record.root)) return disabled("pairing_needed", "retired root");
    if (!(await keyPresent(record.root, { strict: true }))) {
      return disabled("paired_key_missing");
    }
    return activeBinding(record.root, env, "paired", true);
  }
  const other = install.clients[CLIENTS.find((name) => name !== client)];
  const root = binding?.root ?? options.root ?? locations.defaultRoot;
  if (!absolute(root)) fail("invalid_state_path");
  let established = binding?.state === "established" && binding.root === root;
  const conflict =
    !!other ||
    (client === "codex" &&
      (keys.some((keyRoot) => keyRoot !== root) || (!established && keys.length > 0)));
  if (!established && conflict) return disabled();
  if (
    client === "codex" &&
    !established &&
    !options.standardClaudeOrigin &&
    options.usesClaude !== false
  )
    return disabled();
  if (conflict && !keys.includes(root)) return disabled();
  return activeBinding(root, env, conflict ? "pairing_needed" : "single");
}

const retiredRoot = (root) => absolute(root) && rootMarker(root, "retired");

const profileMarkerPath = (root) => join(root, ".cairn-memory-profile", "legacy.json");
const bindingHistoryPath = (root) => join(root, ".cairn-memory-profile", "binding.json");
const identityFingerprint = (key) =>
  createHmac("sha256", key).update("cairn-memory:binding:v1").digest("hex");

async function readBindingHistory(profileRoot) {
  const directory = join(profileRoot, ".cairn-memory-profile");
  if (!(await probe(() => lstat(directory), undefined))) return { state: "absent" };
  let entry;
  try {
    entry = await lstat(bindingHistoryPath(profileRoot));
  } catch (error) {
    return { state: ["ENOENT", "ENOTDIR"].includes(error.code) ? "absent" : "invalid" };
  }
  if (!entry) return { state: "absent" };
  const value = await probe(async () => {
    await checkedPath(directory, { directory: true });
    return jsonFile(bindingHistoryPath(profileRoot));
  }, undefined);
  if (
    value?.version !== 1 ||
    value.profileRoot !== profileRoot ||
    !absolute(value.root) ||
    !/^[0-9a-f]{64}$/.test(value.fingerprint)
  )
    return { state: "invalid" };
  return { state: "valid", ...value };
}

// Only explicit reset may replace recorded scope. No option-clearing/leave side effect.
async function writeBindingHistory(profileRoot, root, { reset = false } = {}) {
  const previous = await readBindingHistory(profileRoot);
  const fingerprint = identityFingerprint(await projectKey(root, { create: false }));
  if (previous.state === "invalid") fail("binding_identity_mismatch");
  if (
    !reset &&
    previous.state === "valid" &&
    (previous.root !== root || previous.fingerprint !== fingerprint)
  )
    fail("binding_identity_mismatch");
  await privateWrite(
    bindingHistoryPath(profileRoot),
    JSON.stringify({
      version: 1,
      profileRoot,
      root,
      fingerprint,
    }),
  );
}

const owned = (info) => typeof process.getuid !== "function" || info.uid === process.getuid();
const probe = async (read, missing) => {
  try {
    return await read();
  } catch {
    return missing;
  }
};

async function rootFacts(root, { strict = false, evidence = false } = {}) {
  const info = await probe(() => stat(root), undefined);
  const usable = !!info?.isDirectory();
  const retired = await rootMarker(root, "retired");
  const sharedMarker = await rootMarker(root, "paired-root");
  const validKey = evidence && (await probe(() => keyPresent(root), false));
  // A present key is not freshness, even if its bytes are invalid. The ordinary
  // identity reader preserves released standalone errors without replacing it.
  const key = !!(await probe(() => lstat(join(root, "project-key")), undefined));
  let error;
  if (strict && !retired) {
    try {
      if (!(await keyPresent(root, { strict: true }))) error = "paired_key_missing";
    } catch (failure) {
      error = failure.code ?? failure.message.split(":")[0];
    }
  }
  return {
    root,
    usable,
    key,
    retired,
    sharedMarker,
    validKey,
    error,
    evidence: evidence && (await probe(() => hasClaudeEvidence(root), false)),
  };
}

/** Every filesystem failure becomes a fact, never another selection path. */
export async function probeClaudeFacts(options = {}) {
  const env = options.env ?? process.env;
  const locations = stateLocations(options);
  const base = locations.home || locations.temporary;
  const homeInfo = await probe(() => stat(base), undefined);
  const homeUsable =
    !!homeInfo?.isDirectory() &&
    (await probe(async () => {
      await access(base, constants.X_OK);
      return true;
    }, false));
  const facts = {
    locations,
    homeUsable,
    pluginRootAbsolute: absolute(locations.claudeRoot),
    coordination: "absent",
    registration: "none",
    install: { version: 1, clients: {} },
    record: undefined,
    canRegister: false,
    platform: options.liveness?.platform ?? process.platform,
    attempt: options.registrationAttempt,
  };
  if (homeUsable) {
    const entry = await probe(() => lstat(locations.coordination), undefined);
    const directory = entry?.isSymbolicLink()
      ? await probe(() => stat(locations.coordination), undefined)
      : entry;
    if (!entry) {
      facts.canRegister = await probe(async () => {
        await access(base, constants.W_OK | constants.X_OK);
        return true;
      }, false);
    } else if (directory?.isDirectory() && owned(directory)) {
      const records = await Promise.all(
        [locations.install, locations.pairing].map((path) =>
          probe(async () => !!(await lstat(path)), "unknown"),
        ),
      );
      try {
        await checkedPath(locations.coordination, { directory: true });
        facts.install = validateInstall(await jsonFile(locations.install));
        facts.record = await jsonFile(locations.pairing);
        if (facts.record) validateRecord(facts.record, locations);
        facts.coordination = "readable";
        facts.canRegister = true;
      } catch {
        if (records.some((value) => value === true || value === "unknown")) {
          // ENOENT is absence, not unreadability of an existing record.
          const knownAbsent = await Promise.all(
            [locations.install, locations.pairing].map(async (path) => {
              try {
                await lstat(path);
                return false;
              } catch (error) {
                return ["ENOENT", "ENOTDIR"].includes(error.code);
              }
            }),
          );
          if (!knownAbsent.every(Boolean)) facts.coordination = "degraded";
        }
        facts.install = { version: 1, clients: {} };
        facts.record = undefined;
      }
    }
  }
  const registration = claudeRegistration(facts.install);
  if (registration) {
    facts.registration =
      registration.profileRoot !== locations.claudeRoot
        ? "other"
        : facts.install.clients.claude
          ? "self-active"
          : "self-retired";
  }
  facts.profile = await rootFacts(locations.claudeRoot);
  facts.bindingHistory = await readBindingHistory(locations.claudeRoot);
  facts.localMarker = "absent";
  const markerPath = profileMarkerPath(locations.claudeRoot);
  const markerDirectory = join(locations.claudeRoot, ".cairn-memory-profile");
  const markerParent = await probe(() => lstat(markerDirectory), undefined);
  let markerEntry;
  if (markerParent) {
    try {
      markerEntry = await lstat(markerPath);
    } catch (error) {
      if (!["ENOENT", "ENOTDIR"].includes(error.code)) facts.localMarker = "invalid";
    }
  }
  if (markerEntry) {
    facts.localMarker = "invalid";
    const marker = await probe(async () => {
      await checkedPath(join(locations.claudeRoot, ".cairn-memory-profile"), { directory: true });
      return jsonFile(markerPath);
    }, undefined);
    if (
      marker?.version === 1 &&
      marker.profileRoot === locations.claudeRoot &&
      marker.root === locations.defaultRoot
    )
      facts.localMarker = "valid";
  }
  // Only an own active binding can authorize probing a non-default shared root.
  if (facts.registration === "self-active") {
    facts.bound = await rootFacts(facts.install.clients.claude.root, {
      strict: !!facts.record && !!facts.install.shared?.ready,
    });
    if (facts.bindingHistory.state === "valid" && facts.bound.key) {
      facts.bound.fingerprint = await probe(
        async () => identityFingerprint(await projectKey(facts.bound.root, { create: false })),
        undefined,
      );
    }
  }
  if (
    facts.registration === "none" &&
    (!facts.profile.key || locations.claudeRoot === locations.defaultRoot)
  ) {
    facts.default = await rootFacts(locations.defaultRoot, {
      evidence: facts.coordination !== "degraded",
    });
  }
  const option = env.CLAUDE_PLUGIN_OPTION_PAIRING_RECORD || undefined;
  const argument = options.pairingRecord || undefined;
  const delivered = argument ?? option;
  facts.delivery =
    delivered === undefined
      ? "none"
      : (argument && option && argument !== option) ||
          !absolute(delivered) ||
          delivered !== locations.pairing
        ? "wrong"
        : "delivered";
  facts.stateDir = env.CAIRN_MEMORY_STATE_DIR;
  return facts;
}

/** The only Claude root/eligibility decision. No I/O, clock, environment or throws. */
export function resolveClaudeBinding(facts) {
  const stop = (status = "pairing_needed", detail) => ({
    enabled: false,
    root: undefined,
    createKey: false,
    status,
    ...(detail ? { detail } : {}),
  });
  const select = (root, createKey, status = "single", detail, paired = false) => {
    if (root.retired) return stop("pairing_needed", "retired root");
    if (root.sharedMarker && !root.key) return stop("paired_key_missing");
    if (paired && root.error) return stop(root.error);
    if (facts.bindingHistory?.state === "valid" && !root.key) return stop("paired_key_missing");
    if (
      facts.bindingHistory?.state === "valid" &&
      (facts.bindingHistory.root !== root.root ||
        facts.bindingHistory.fingerprint !== root.fingerprint)
    )
      return stop("binding_identity_mismatch");
    if (!createKey && !root.key)
      return stop(paired ? "paired_key_missing" : "standalone_key_missing", detail);
    if (paired && facts.stateDir !== undefined && facts.stateDir !== root.root)
      return stop("state_dir_mismatch");
    return {
      enabled: true,
      root: root.root,
      createKey,
      status,
      paired,
      ...(detail ? { detail } : {}),
      register:
        !paired &&
        facts.registration === "none" &&
        facts.coordination !== "degraded" &&
        facts.canRegister &&
        facts.pluginRootAbsolute &&
        facts.platform !== "win32" &&
        !facts.attempt,
    };
  };
  if (facts.delivery === "wrong") return stop("pairing_record_mismatch");
  if (facts.bindingHistory && facts.bindingHistory.state !== "absent") {
    if (
      facts.bindingHistory.state !== "valid" ||
      facts.coordination !== "readable" ||
      !["self-active", "self-retired"].includes(facts.registration) ||
      (facts.install.shared && !facts.record)
    )
      return stop("pairing_record_missing");
  }
  if (facts.coordination === "absent" && facts.localMarker !== "absent")
    return stop("pairing_record_missing");
  if (facts.coordination === "degraded") {
    if (facts.delivery !== "none") return stop("pairing_needed", "coordination unreadable");
    if (facts.profile.key)
      return select(facts.profile, false, "standalone_unregistered", "coordination unreadable");
    if (facts.localMarker === "valid")
      return select(facts.default, false, "standalone_unregistered", "coordination unreadable");
    return stop("pairing_needed", "coordination unreadable");
  }
  if (facts.delivery !== "none" && !facts.record) return stop("pairing_record_missing");
  if (facts.registration === "other") {
    if (facts.delivery !== "none") return stop("pairing_record_mismatch");
    return select(facts.profile, true, "standalone_unregistered");
  }
  if (facts.registration === "self-retired" || facts.install.resetPending) return stop();
  const binding = facts.install.clients.claude;
  if (facts.record || facts.install.shared || binding?.state === "pending") {
    const shared = facts.install.shared;
    if (!facts.record || facts.delivery === "none" || !shared?.ready) return stop();
    if (facts.platform === "win32") return stop("pairing_platform_unsupported");
    if (
      !binding ||
      binding.state !== "established" ||
      binding.root !== facts.record.root ||
      !shared.initialized ||
      shared.id !== facts.record.id ||
      shared.root !== facts.record.root ||
      shared.policy !== facts.record.policy
    )
      return stop("pairing_record_mismatch");
    return select(facts.bound, false, "paired", undefined, true);
  }
  if (facts.registration === "self-active") {
    if (facts.install.clients.codex && !facts.bound.key) return stop();
    return select(facts.bound, true, facts.install.clients.codex ? "pairing_needed" : "single");
  }
  const codex = facts.install.clients.codex;
  if (!codex && facts.localMarker !== "absent") return stop("pairing_record_missing");
  let root = facts.profile;
  const createKey = true;
  if (
    facts.pluginRootAbsolute &&
    !root.key &&
    facts.default?.validKey &&
    !facts.default.sharedMarker &&
    facts.default.evidence
  ) {
    root = facts.default;
  }
  const legacy =
    root.root === facts.default?.root &&
    facts.default.validKey &&
    facts.default.evidence &&
    !facts.default.sharedMarker;
  if (codex && (!root.key || (codex.root === root.root && !legacy))) return stop();
  return select(
    root,
    createKey,
    codex ? "pairing_needed" : facts.attempt === "busy" ? "standalone_unregistered" : "single",
  );
}

async function resolveClaudeClient(options) {
  let facts = await probeClaudeFacts(options);
  let binding = resolveClaudeBinding(facts);
  if (binding.register) {
    try {
      binding = await locked(
        { ...options, claudeFacts: true, timeoutMs: options.timeoutMs ?? 100 },
        async (current) => {
          const selected = resolveClaudeBinding(current);
          if (selected.register) {
            if (
              selected.root === current.locations.defaultRoot &&
              selected.root !== current.locations.claudeRoot
            ) {
              await privateWrite(
                profileMarkerPath(current.locations.claudeRoot),
                JSON.stringify({
                  version: 1,
                  profileRoot: current.locations.claudeRoot,
                  root: selected.root,
                }),
              );
            }
            current.install.clients.claude = {
              root: selected.root,
              profileRoot: current.locations.claudeRoot,
              state: "established",
            };
            await saveInstall(current.locations, current.install);
          }
          return selected;
        },
      );
    } catch (error) {
      facts = await probeClaudeFacts({
        ...options,
        registrationAttempt: error.message === "setup_busy" ? "busy" : "skipped",
      });
      binding = resolveClaudeBinding(facts);
    }
  }
  if (binding.enabled) {
    binding.workerEnv = { ...(options.env ?? process.env), CAIRN_MEMORY_STATE_DIR: binding.root };
    if (options.initialize) await identityForBinding(binding, "claude");
  }
  return binding;
}

/** Claude decisions never share the setup/Codex detector's exception path. */
export async function resolveClient(options = {}) {
  const client = options.client ?? "claude";
  if (!CLIENTS.includes(client)) fail("invalid_client");
  if (client === "claude") return resolveClaudeClient(options);
  const snapshot = await detectClients(options);
  let binding = await selectCodexBinding(options, snapshot, options.pairingRecord || undefined);
  if (binding.enabled && !binding.paired && !snapshot.install.clients.codex) {
    binding = await locked(options, async (current) => {
      const selected = await selectCodexBinding(
        options,
        current,
        options.pairingRecord || undefined,
      );
      if (selected.enabled && !selected.paired && !current.install.clients.codex) {
        current.install.clients.codex = { root: selected.root, state: "established" };
        await saveInstall(current.locations, current.install);
      }
      return selected;
    });
  }
  if (binding.enabled && options.initialize) await identityForBinding(binding, client);
  return binding;
}

async function identityForBinding(binding, client, cwd = "initialization") {
  return opaqueProjectId(
    binding.root,
    cwd,
    binding.paired || client !== "claude"
      ? { strict: true, create: !binding.paired }
      : binding.createKey === false
        ? { create: false }
        : undefined,
  );
}

export async function clientProjectId(options, cwd, binding) {
  if (!cwd) return undefined;
  binding ??= await resolveClient(options);
  if (!binding.enabled) fail(binding.status);
  return identityForBinding(binding, options.client ?? "claude", cwd);
}

/** CX-7 API: no host execution. Caller obtains consent and stops hosts/workers. */
export async function initializePairing(options = {}) {
  const setupOptions = { ...options, setup: true };
  const locations = stateLocations(setupOptions); // refuse bad home before writes
  if (
    options.hostsStopped !== true ||
    !CLIENTS.every((client) => options.consent?.[client] === true)
  )
    fail("pairing_consent_required");
  const root = options.root ?? locations.defaultRoot;
  durable(root, locations);
  if ((await retiredRoot(root)) || (await retiredRoot(options.adoptFrom)))
    return disabled("retired_root");
  if (options.adoptFrom) await requireTemporarySource(options.adoptFrom, locations);
  const initial = await detectClients(setupOptions);
  if (initial.record && !initial.install.shared) fail("pairing_record_mismatch");
  const profileRoot = normalizeRoot(
    options.claudeProfileRoot ??
      claudeRegistration(initial.install)?.profileRoot ??
      (options.env ?? process.env).CLAUDE_PLUGIN_DATA ??
      (options.standardClaudeOrigin === true ? locations.knownClaudeRoot : undefined),
  );
  if (profileRoot === undefined) return disabled("claude_profile_root_required");
  if (!absolute(profileRoot)) fail("invalid_claude_profile_root");
  const registeredProfile = claudeRegistration(initial.install)?.profileRoot;
  if (registeredProfile !== undefined && registeredProfile !== profileRoot)
    fail("claude_profile_mismatch");
  if (!options.standardClaudeOrigin && options.usesClaude === undefined)
    return { status: "claude_confirmation_needed", enabled: false };
  if (
    !initial.install.shared &&
    (initial.keys.length ||
      Object.keys(initial.install.clients).length ||
      options.usesClaude === true) &&
    options.adopt !== true
  )
    return disabled();
  return locked(setupOptions, async ({ install, keys, record: existingRecord }) => {
    if ((await retiredRoot(root)) || (await retiredRoot(options.adoptFrom)))
      return disabled("retired_root");
    if (options.adoptFrom) await requireTemporarySource(options.adoptFrom, locations);
    const registration = claudeRegistration(install);
    if (registration && registration.profileRoot !== profileRoot) fail("claude_profile_mismatch");
    const history = await readBindingHistory(profileRoot);
    if (history.state === "invalid" || (history.state === "valid" && history.root !== root))
      fail("binding_identity_mismatch");
    if (history.state === "valid" && !(await keyPresent(root)))
      return disabled("paired_key_missing");
    if (existingRecord && (!install.shared || !install.shared.initialized))
      fail("pairing_record_mismatch");
    if (install.resetPending) fail("identity_reset_pending");
    if (
      install.shared &&
      (install.shared.root !== root || (existingRecord && existingRecord.id !== install.shared.id))
    )
      fail("pending_binding_mismatch");
    if (!install.shared) {
      if (
        (keys.length || Object.keys(install.clients).length || options.usesClaude === true) &&
        options.adopt !== true
      )
        return disabled();
      if (options.adoptFrom && !options.adopt) fail("adoption_confirmation_required");
      if (options.adopt && !(await keyPresent(options.adoptFrom ?? root)))
        fail("adopted_key_missing");
      if (
        options.adoptFrom &&
        (await keyPresent(root)) &&
        (await projectKey(root, { create: false })) !==
          (await projectKey(options.adoptFrom, { create: false }))
      )
        fail("adoption_key_conflict");
      install.shared = {
        id: randomUUID(),
        root,
        policy: options.adopt ? "adopt-existing" : "initialize-shared",
        initialized: false,
        ready: false,
        ...(options.adoptFrom ? { adoptFrom: options.adoptFrom } : {}),
      };
      for (const client of CLIENTS)
        install.clients[client] = {
          root,
          state: "pending",
          ...(client === "claude" ? { profileRoot } : {}),
        };
      await saveInstall(locations, install);
      await options.checkpoint?.("binding-written");
    }
    if (options.adoptFrom && (!options.adopt || install.shared.adoptFrom !== options.adoptFrom))
      fail("pending_binding_mismatch");
    if (!install.shared.initialized) {
      if (install.shared.adoptFrom && !(await keyPresent(root))) {
        const source = await projectKey(install.shared.adoptFrom, { create: false });
        await projectKey(root, { originalKey: source, checkpoint: options.checkpoint });
        if ((await projectKey(root, { create: false })) !== source) fail("adoption_key_conflict");
      }
      // Retrying after publication always reads the winner. Adoption never creates.
      await projectKey(root, {
        create: install.shared.policy === "initialize-shared",
        checkpoint: options.checkpoint,
      });
      install.shared.initialized = true;
      await saveInstall(locations, install);
      await options.checkpoint?.("initialized");
    } else if (!(await keyPresent(root, { strict: true }))) return disabled("paired_key_missing");
    // Root-local history survives loss or replacement of the coordination directory.
    await markPairRoot(root);
    await writeBindingHistory(profileRoot, root);
    const record = {
      version: 1,
      id: install.shared.id,
      root,
      participants: CLIENTS,
      policy: install.shared.policy,
    };
    await privateWrite(locations.pairing, JSON.stringify(record));
    // Establish the EOF barrier before either client can become active.
    if (!install.shared.barrier) {
      const before = await readControlState(root);
      await setPaused(root, true, { rotate: true });
      if (!before.paused) await setPaused(root, false);
      install.shared.barrier = true;
      await saveInstall(locations, install);
    }
    return {
      status: install.shared.ready ? "paired" : "binding_pending",
      enabled: install.shared.ready,
      pairingRecord: locations.pairing,
      root,
    };
  });
}

/** Call only after BOTH hook configurations have the record and workers are stopped. */
export async function completePairing(options = {}) {
  if (
    options.hostsStopped !== true ||
    !CLIENTS.every((client) => options.configured?.[client] === true)
  )
    fail("binding_configuration_required");
  return locked({ ...options, setup: true }, async ({ install, record, locations }) => {
    if (install.resetPending) fail("identity_reset_pending");
    if (
      !record ||
      !install.shared?.initialized ||
      !install.shared.barrier ||
      install.shared.id !== record.id ||
      install.shared.root !== record.root
    )
      fail("pending_binding_mismatch");
    if (await retiredRoot(record.root)) return disabled("retired_root");
    if (!(await keyPresent(record.root, { strict: true }))) return disabled("paired_key_missing");
    for (const client of CLIENTS)
      install.clients[client] = {
        ...install.clients[client],
        root: record.root,
        state: "established",
      };
    await markPairRoot(record.root);
    await writeBindingHistory(install.clients.claude.profileRoot, record.root);
    install.shared.ready = true;
    await saveInstall(locations, install);
    return { status: "paired", enabled: true, pairingRecord: locations.pairing, root: record.root };
  });
}

/** Explicit stopped-worker identity reset; old roots and memories are retained. */
export async function resetIdentity(options = {}) {
  if (
    options.confirmIdentityReset !== true ||
    options.hostsStopped !== true ||
    !CLIENTS.includes(options.primaryClient)
  )
    fail("identity_reset_confirmation_required");
  const locations = stateLocations({ ...options, setup: true });
  durable(options.root, locations);
  return locked({ ...options, setup: true }, async ({ install, record, keys }) => {
    if (await retiredRoot(options.root)) return disabled("retired_root");
    if (
      !install.shared ||
      (!record && !install.resetPending) ||
      options.root === install.shared.root ||
      (keys.includes(options.root) && !install.resetPending)
    )
      fail("identity_reset_requires_new_root");
    if (install.resetPending && install.resetPending.root !== options.root)
      fail("pending_binding_mismatch");
    install.resetPending = { root: options.root, client: options.primaryClient };
    await saveInstall(locations, install);
    // Retire the old root before the new identity can become active. Retrying a
    // stopped-host reset may rotate again, but never re-enables old workers.
    await setPaused(install.shared.root, true, { rotate: true });
    await privateWrite(
      join(install.shared.root, "retired"),
      JSON.stringify({ version: 1, retired: true }),
    );
    await projectKey(options.root);
    await markPairRoot(options.root);
    await writeBindingHistory(install.clients.claude.profileRoot, options.root, { reset: true });
    await setPaused(options.root, true, { rotate: true });
    const retired = [
      ...(install.retired ?? []),
      { ...install.shared, invalidated: true, claude: { ...install.clients.claude } },
    ];
    await unlink(locations.pairing).catch((error) => {
      if (error.code !== "ENOENT") throw error;
    });
    await saveInstall(locations, {
      version: 1,
      retired,
      clients: {
        [options.primaryClient]: {
          root: options.root,
          state: "established",
          initialized: true,
          ...(options.primaryClient === "claude"
            ? { profileRoot: install.clients.claude.profileRoot }
            : {}),
        },
      },
    });
    return {
      status: "identity_reset",
      root: options.root,
      disclosure:
        "Old project memories are no longer addressable by the new identity; " +
        "the second client requires explicit adoption. Resume starts at EOF.",
    };
  });
}

// All successful pair-root operations publish through this single helper.
async function markPairRoot(root) {
  await privateWrite(join(root, "paired-root"), JSON.stringify({ version: 1, paired: true }));
}

/** Explicit original-backup repair, under the setup lock with both hosts stopped. */
export async function repairIdentity(options = {}) {
  if (options.hostsStopped !== true || options.confirmKeyRepair !== true)
    fail("key_repair_confirmation_required");
  return locked({ ...options, setup: true }, async ({ install }) => {
    const root = options.root;
    if (
      !absolute(root) ||
      (root !== install.shared?.root &&
        !Object.values(install.clients).some((client) => client.root === root))
    )
      fail("pairing_record_mismatch");
    if (await retiredRoot(root)) return disabled("retired_root");
    const profileRoot = claudeRegistration(install)?.profileRoot;
    const history = await readBindingHistory(profileRoot);
    if (
      history.state !== "valid" ||
      history.root !== root ||
      history.fingerprint !== identityFingerprint(options.originalKey ?? "")
    )
      fail("repair_key_conflict");
    await restoreProjectKey(root, options.originalKey);
    await markPairRoot(root);
    await writeBindingHistory(profileRoot, root);
    return { status: "key_restored", root };
  });
}

/** Mutation inventory: tests exercise every operation, including adoption separately. */
export const PAIR_ROOT_OPERATIONS = Object.freeze([
  { name: "initialize", run: initializePairing },
  { name: "adopt", run: initializePairing },
  { name: "complete", run: completePairing },
  { name: "reset", run: resetIdentity },
  { name: "repair", run: repairIdentity },
]);
