import { createHash } from "node:crypto";
import { redactSecrets } from "./redact.mjs";

// 0.1.1 privacy filter (the second D1 exception, chichi 2026-09-29). Claude Code
// writes some user-role records itself; they are not the person's words and are
// never sent. Kept records are parsed exactly as in 0.1.0.
export const MACHINE_TEXT_PREFIXES = Object.freeze([
  "<command-name>",
  "<command-message>",
  "<command-args>",
  "<local-command-stdout>",
  "<local-command-stderr>",
  "<local-command-caveat>",
  "[Image: source:",
  "<bash-input>",
  "<bash-stdout>",
  "<bash-stderr>",
  "<system-reminder>",
  "<user-prompt-submit-hook>",
  "<task-notification>",
]);

// `promptSource` values Claude Code 2.1.283 writes on prompts a person submitted:
// "sdk" in print mode and "typed" in the interactive TUI. Machine records carry
// none. Older hosts may omit it, so it only protects typed text from the prefix
// rule; it is never required.
export const TYPED_PROMPT_SOURCES = Object.freeze(["sdk", "typed"]);

function textBlocks(content) {
  if (typeof content === "string") return [content];
  if (!Array.isArray(content)) return [];
  return content.flatMap((block) =>
    block && block.type === "text" && typeof block.text === "string"
      ? [block.text]
      : [],
  );
}

function carriesToolResult(record) {
  const content = record?.message?.content;
  return (
    record?.toolUseResult !== undefined ||
    (Array.isArray(content) && content.some((block) => block?.type === "tool_result"))
  );
}

/**
 * Why a user record was generated by Claude Code rather than typed, or null.
 * Structural flags always exclude; a wrapper prefix excludes unless
 * `promptSource` marks the record as a submitted prompt.
 */
export function machineUserRecord(record) {
  if (record?.isMeta) return "meta";
  if (record?.isCompactSummary) return "compact-summary";
  if (carriesToolResult(record)) return "tool-result";
  if (TYPED_PROMPT_SOURCES.includes(record?.promptSource)) return null;
  const text = textBlocks(record?.message?.content).join("\n").trimStart();
  return MACHINE_TEXT_PREFIXES.some((prefix) => text.startsWith(prefix))
    ? "machine-wrapper"
    : null;
}

// Claude records slash commands as command XML, and Skill tool expansion as
// an isMeta user message headed by its base directory. Inspect these markers,
// never conversational mentions or the skill's instructions/arguments.
function startsPluginSkill(record) {
  const blocks = record?.message?.content;
  if (record.type === "assistant" && Array.isArray(blocks) && blocks.some(
    (block) => block?.type === "tool_use" && block.name === "Skill" &&
      /^cairn-memory:[\w-]+$/.test(block.input?.skill ?? ""),
  )) return true;
  if (record.type !== "user") return false;
  const text = textBlocks(blocks).join("\n").trimStart();
  if (record.isMeta) {
    const directory = /^Base directory for this skill: ([^\r\n]+)/.exec(text)?.[1];
    if (directory && /(?:^|\/)cairn-memory\/(?:[^/]+\/)*skills\/[^/]+\/?$/.test(
      directory.replaceAll("\\", "/"),
    )) return true;
  }
  if (TYPED_PROMPT_SOURCES.includes(record.promptSource) && !record.isMeta) return false;
  if (!/^<command-(?:name|message)>/.test(text)) return false;
  const name = /<command-name>([^<]+)<\/command-name>/.exec(text)?.[1] ??
    /<command-message>([^<]+)<\/command-message>/.exec(text)?.[1];
  return /^\/?cairn-memory:[\w-]+$/.test(name ?? "");
}

function pluginControlOutput(text) {
  // Whole single-line outputs from hook.mjs control(), including quota notices.
  // A quote in a longer answer is still ordinary conversation.
  if (text.includes("\n") || text.includes("\r")) return false;
  return text.startsWith("Cairn automatic memory: ") ||
    text === "Cairn automatic memory is paused." ||
    text.startsWith("Cairn automatic memory is active.") ||
    text === "Cairn quota state repaired to open; automatic memory is active.";
}

/**
 * Every message 0.1.0 would parse, in order and with the same ids and content,
 * each marked `withheld` when 0.1.1 does not send it. Batch boundaries and event
 * ids are computed over all of them, so they stay exactly as 0.1.0 had them.
 * Optional turnState carries only a boolean across incremental capture windows;
 * it is updated even by tool-only records that the old parser did not emit.
 */
export function transcriptWindow(jsonl, sessionId, { turnState = {} } = {}) {
  const messages = [];
  for (const [lineIndex, line] of jsonl.split("\n").entries()) {
    if (!line.trim()) continue;
    let record;
    try {
      record = JSON.parse(line);
    } catch {
      continue;
    }
    if (record?.type !== "user" && record?.type !== "assistant") continue;
    const role = record.type;
    const machine = role === "user" && Boolean(machineUserRecord(record));
    if (startsPluginSkill(record)) turnState.ownSkillTurn = true;
    else if (role === "user" && !machine) turnState.ownSkillTurn = false;
    const rawText = textBlocks(record?.message?.content).join("\n").trim();
    const content = textBlocks(record?.message?.content)
      .map(redactSecrets)
      .join("\n")
      .trim()
      .slice(0, 20_000);
    if (!content) continue;
    const id =
      typeof record.uuid === "string" && record.uuid
        ? record.uuid
        : createHash("sha256")
            .update(`${sessionId}\0${lineIndex}\0${role}\0${content}`)
            .digest("hex");
    messages.push({ id, role, content, withheld: machine || turnState.ownSkillTurn === true ||
      (role === "assistant" && pluginControlOutput(rawText)) });
  }
  return messages;
}

const strip = ({ id, role, content }) => ({ id, role, content });

/** The messages 0.1.1 sends. */
export function transcriptMessages(jsonl, sessionId) {
  return transcriptWindow(jsonl, sessionId).filter((message) => !message.withheld).map(strip);
}

/** The messages 0.1.0 sent; used for batch identity and tests, never for sending. */
export function legacyTranscriptMessages(jsonl, sessionId) {
  return transcriptWindow(jsonl, sessionId).map(strip);
}

export function captureEventId(sessionId, messages) {
  return createHash("sha256")
    .update(`${sessionId}\0${messages.map((message) => message.id).join("\0")}`)
    .digest("hex");
}
