import { createHash } from "node:crypto";
import { redactSecrets } from "./redact.mjs";

// 0.1.1 privacy filter (the second D1 exception, chichi 2026-09-29). Claude Code
// writes some user-role records itself; they are not the person's words and are
// never sent. Kept records are parsed exactly as in 0.1.0.
export const MACHINE_TEXT_PREFIXES = Object.freeze([
  "<command-name>",
  "<command-message>",
  "<command-args>",
  "<local-command-stdout>",
  "<local-command-stderr>",
  "<local-command-caveat>",
  "[Image: source:",
  "<bash-input>",
  "<bash-stdout>",
  "<bash-stderr>",
  "<system-reminder>",
  "<user-prompt-submit-hook>",
  "<task-notification>",
]);

// `promptSource` values Claude Code 2.1.283 writes on prompts a person submitted:
// "sdk" in print mode and "typed" in the interactive TUI. Machine records carry
// none. Older hosts may omit it, so it only protects typed text from the prefix
// rule; it is never required.
export const TYPED_PROMPT_SOURCES = Object.freeze(["sdk", "typed"]);

function textBlocks(content) {
  if (typeof content === "string") return [content];
  if (!Array.isArray(content)) return [];
  return content.flatMap((block) =>
    block && block.type === "text" && typeof block.text === "string"
      ? [block.text]
      : [],
  );
}

function carriesToolResult(record) {
  const content = record?.message?.content;
  return (
    record?.toolUseResult !== undefined ||
    (Array.isArray(content) && content.some((block) => block?.type === "tool_result"))
  );
}

/**
 * Why a user record was generated by Claude Code rather than typed, or null.
 * Structural flags always exclude; a wrapper prefix excludes unless
 * `promptSource` marks the record as a submitted prompt.
 */
export function machineUserRecord(record) {
  if (record?.isMeta) return "meta";
  if (record?.isCompactSummary) return "compact-summary";
  if (carriesToolResult(record)) return "tool-result";
  if (TYPED_PROMPT_SOURCES.includes(record?.promptSource)) return null;
  const text = textBlocks(record?.message?.content).join("\n").trimStart();
  return MACHINE_TEXT_PREFIXES.some((prefix) => text.startsWith(prefix))
    ? "machine-wrapper"
    : null;
}

function parseMessages(jsonl, sessionId, filterMachineRecords) {
  const messages = [];
  for (const [lineIndex, line] of jsonl.split("\n").entries()) {
    if (!line.trim()) continue;
    let record;
    try {
      record = JSON.parse(line);
    } catch {
      continue;
    }
    if (record?.type !== "user" && record?.type !== "assistant") continue;
    const role = record.type;
    if (filterMachineRecords && role === "user" && machineUserRecord(record)) continue;
    const content = textBlocks(record?.message?.content)
      .map(redactSecrets)
      .join("\n")
      .trim()
      .slice(0, 20_000);
    if (!content) continue;
    const id =
      typeof record.uuid === "string" && record.uuid
        ? record.uuid
        : createHash("sha256")
            .update(`${sessionId}\0${lineIndex}\0${role}\0${content}`)
            .digest("hex");
    messages.push({ id, role, content });
  }
  return messages;
}

export function transcriptMessages(jsonl, sessionId) {
  return parseMessages(jsonl, sessionId, true);
}

/**
 * The 0.1.0 parse, kept only to retry a window 0.1.0 had already frozen, so its
 * batches and event ids stay identical across the upgrade.
 */
export function legacyTranscriptMessages(jsonl, sessionId) {
  return parseMessages(jsonl, sessionId, false);
}

export function captureEventId(sessionId, messages) {
  return createHash("sha256")
    .update(`${sessionId}\0${messages.map((message) => message.id).join("\0")}`)
    .digest("hex");
}
